### ISSUE TITLE
How to use nonce returnd by HS1 minner to submitwork to nodes?

### ISSUE THREAD

**Issue by ruyichang** [HandyMiner/HandyMiner-Goldshell-CLI#10]
Hi there,
I'v tested it on HNS MAINNET by HS1
Following is the logs Interactive journal of my test，

```
//subscribe
{"method":"mining.subscribe","id":0,"params":["icbtminer"]}
//authorize
{"method":"mining.authorize","id":1,"params":["GoldShell.H10B0291C354D4","x"]}

{"id":0,"result":[[["mining.set_difficulty","ae000000"],["mining.notify","ae000000"]],"ae000000",24],"error":null}
{"id":null,"method":"mining.set_difficulty","params":[128]}

{"id": 1, "result": true, "error": null}


//notify
{"id":null,"method":"mining.notify","params":["3","00000000000000005a15f73435b4b326894a88acafaa5bd2854435a108fb2060","9d5ea4e0b886a02fa8cb6ac14eb56de194c69111197a3dc3d31dcfeb3d49c6a7","31ec2ee912ceeef819ea37b5e1c35e64746c77413a01e8617a46c48fe6bca046","4a4d980553ed32d1819780c190a0a9947210af17cfcd92a085ae073b2c7f3a1b","0000000000000000000000000000000000000000000000000000000000000000","00000000","1906292f","5fc5a7b8"]}

//submit
{"method":"mining.submit","id":2,"params":["GoldShell.H10B0291C354D4","3","00000002","5fc5a7b8","ed796623","0000000000000000000000000000000000000000000000000000000000000000"]}
```
               ----------------------------------
               |
               ⬇
//submit parse
```
"blockin.H10B0291C354D4",  //username
"3",                       //jobID
"00000002",                //nonce2
"5fc5a7b8",                //response.nonce.slice(0,8) time
"ed796623",                //response.nonce.slice(8,16)
"0000000000000000000000000000000000000000000000000000000000000000"  //mask  ???
```
How to get the extraNonce(24 Bytes) required by the node via nonce/nonce2 of mining.submit .
Also, the last field is mask?

Thank you very much.

**Comment by smcki012** [comment]
Directions for using HandyMiner Goldshell CLI can be found here. 

https://handyminer.github.io/HandyMiner-Goldshell-CLI/index.html

Closing this issue.

**Comment by ruyichang** [comment]
> Directions for using HandyMiner Goldshell CLI can be found here

Thanks for the guidance, but I am already using HS1 miner normally. What I want to consult is how to use the data returned by the miner, not how to use the miner in the link just now. Sorry, where can I get the explanation about HNS extranonce/eonce.

**Comment by smcki012** [comment]
You can learn more on the Handshake HSD GitHub if you search in the issues. Can also learn more here http://hsd-dev.org. There isn't much materials for mining education. And, we don't have the time or incentive to educate.
